update

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -19,35 +19,39 @@ build:
     - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
     - docker push $IMAGE_NAME:latest
   only:
-    - prod
+    - main
 
 deploy:
   stage: deploy
   image: alpine:latest
   before_script:
     - apk add --no-cache openssh-client
+    - |
+      if [ -z "$VPS_HOST" ] || [ -z "$VPS_USER" ] || [ -z "$SSH_PRIVATE_KEY" ]; then
+        echo "ERROR: VPS_HOST, VPS_USER, or SSH_PRIVATE_KEY is missing. Check if 'main' is a Protected Branch or Unprotect your variables."
+        exit 1
+      fi
     - mkdir -p ~/.ssh
     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/deploy_key
     - chmod 600 ~/.ssh/deploy_key
     - ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts
   script:
     - |
-      ssh -i ~/.ssh/deploy_key $VPS_USER@$VPS_HOST << 'EOF'
-
-        echo "Login registry"
+      ssh -i ~/.ssh/deploy_key $VPS_USER@$VPS_HOST << EOF
+        set -e
+        echo "Login to registry..."
         echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.gitlab.com
 
-        echo "Pull image"
-        docker pull registry.gitlab.com/awdpay/event-frontend:latest
+        echo "Pulling latest image..."
+        docker pull $IMAGE_NAME:latest
 
-        echo "Stop old container"
+        echo "Restarting container..."
         docker stop event_frontend || true
         docker rm event_frontend || true
 
-        echo "Run new container"
-        docker run -d --name event_frontend -p 3000:80 registry.gitlab.com/awdpay/event-frontend:latest
+        docker run -d --name event_frontend -p 3000:80 $IMAGE_NAME:latest
 
-        echo "Frontend déployé avec succès"
+        echo "Frontend déployé avec succès!"
       EOF
   only:
-    - prod
+    - main
